# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---

ingress:
  basic_auth: false
  class: ""
  hostname: null
  tls_secret: null

os2mo:
  replicaCount: 1

  image:
    repository: magentaaps/os2mo
    tag: azure
    pullPolicy: IfNotPresent

  port: 80

lora:
  replicaCount: 1

  image:
    repository: magentaaps/lora
    tag: azure
    pullPolicy: IfNotPresent

moxdb:
  replicaCount: 1

  image:
    repository: magentaaps/postgres-os2mo
    tag: 10-11.7-test
    pullPolicy: IfNotPresent

dipex:
  replicaCount: 1

  image:
    repository: magentaaps/dipex
    tag: feature_dipex_in_docker
    pullPolicy: IfNotPresent

  settings:
    mox.base: "http://mox-service:80"
    mora.base: "http://mo-service:80"

    crontab.RUN_IMPORTS_DUMMY: true

    crontab.SVC_USER: "USER@KOMMUNE.NET"
    crontab.SVC_KEYTAB: "/tmp/keytab-file"
    crontab.CRON_BACKUP: "/tmp/backup-dir"
    crontab.CRON_LOG_FILE: "/tmp/cron-log-file"
    crontab.CRON_LOG_JSON_SINK: "/tmp/log.json"
    crontab.BACKUP_SAVE_DAYS: "60"
    crontab.SNAPSHOT_LORA: "/tmp/db-snapshot.sql"
    crontab.OS2MO_COMPOSE_YML: "/tmp/to/os2mo/docker-compose.yml"

  secrets: {}


nameOverride: ""
fullnameOverride: ""

load_fixture: false
