# SPDX-FileCopyrightText: Magenta ApS
# SPDX-License-Identifier: MPL-2.0

# Each Terraform resource is applied using a `tf-runner` pod deployed in its
# namespace. The tf-controller's chart creates a default ServiceAccount in the
# flux-system namespace, as well as a cluster-wide ClusterRole, so Terraform
# resources in this namespace can be applied.
# This makes sense for the GitOps model, but in the OS2mo chart we want each
# integration to deploy Terraform resources for their backing services or to
# get keycloak tokens. Therefore, we must create a `tf-runner` ServiceAccount
# in the namespace of the chart release with the same role binding.
# See https://github.com/weaveworks/tf-controller/issues/59.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-runner  # the default name used by runners
