# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Global
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  HELM_REPO: https://chartmuseum.magentahosted.dk
  REVIEW_VERSION: 0.0.0-mr$CI_MERGE_REQUEST_IID
  REVIEW_CHART_URL: $HELM_REPO/api/charts/os2mo/$REVIEW_VERSION
  REVIEW_URL: https://chart-mr$CI_MERGE_REQUEST_IID.moraci.magentahosted.dk

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .venv/
    - .cache/pip
    - .cache/pre-commit

stages:
  - lint
  - test
  - review
  - release
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID

include:
  - project: 'labs/salt-automation'
    ref: 'master'
    file: '/gitlab-ci-templates/common/autopub.v1.yml'
  - project: "labs/salt-automation"
    ref: "master"
    file: "/gitlab-ci-templates/common/config-updater-meta.v1.yml"

# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------
.install-deps-template: &install-deps
  before_script:
    # Install pre-commit
    - pip install pre-commit
    # Install yamllint
    - pip install yamllint
    # Install shellcheck
    - apt-get update && apt-get install -y shellcheck
    # Install Helm
    - curl https://baltocdn.com/helm/signing.asc | apt-key add -
    - apt-get update && apt-get install -y apt-transport-https coreutils
    - |-
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" |
        tee /etc/apt/sources.list.d/helm-stable-debian.list
    - apt-get update && apt-get install -y helm

.lint-template: &lint
  <<: *install-deps
  image: python:3.8
  stage: lint

.test-template: &test
  <<: *install-deps
  image: python:3.8
  stage: test

# ---------------------------------------------------------------------------
# Lint
# ---------------------------------------------------------------------------
Lint Project:
  <<: *lint
  script:
    - pre-commit run --all-files

Lint Chart:
  stage: lint
  image: quay.io/helmpack/chart-testing:v3.4.0
  script:
    - ct lint --all --chart-dirs .


# ---------------------------------------------------------------------------
# Test
# ---------------------------------------------------------------------------
Generate Project:
  <<: *test
  script:
    - helm template --kube-version 1.19.11 chart/


Release version:
  stage: release
  needs: []
  image:
    name: alpine/helm:3.7.1
    entrypoint: [""]
  tags:
    - docker
  before_script:
    - helm plugin install https://github.com/chartmuseum/helm-push.git
    - helm repo add magenta-chartmuseum $HELM_REPO
  script:
    - helm cm-push --version=$CI_COMMIT_TAG chart magenta-chartmuseum
  rules:
    - if: $CI_COMMIT_TAG =~ /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/


pages:
  image: python:3.8
  stage: release
  needs: []
  before_script:
    - pip install mkdocs-material
    - pip install mkdocs-autorefs
  script:
    - mkdocs build --strict --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG =~ /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/

# Review Stage
##############
deploy_helm_chart:
  stage: review
  needs: []
  image:
    name: alpine/helm:3.7.1
    entrypoint: [""]
  tags:
    - docker
  before_script:
    - helm plugin install https://github.com/chartmuseum/helm-push.git
    - helm repo add magenta-chartmuseum $HELM_REPO
  script:
    - helm cm-push --version=$REVIEW_VERSION --force chart magenta-chartmuseum
  environment:
    name: chart/$CI_MERGE_REQUEST_IID
    url: $REVIEW_CHART_URL
    on_stop: stop_helm_chart
    auto_stop_in: 1 week
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true

stop_helm_chart:
  stage: review
  needs: []
  image: alpine:3
  variables:
    GIT_STRATEGY: none # We do not need the source code
  tags:
    - docker
  before_script:
    - apk add curl
  script:
    - curl -X DELETE -u $HELM_REPO_USERNAME:$HELM_REPO_PASSWORD $REVIEW_CHART_URL
  environment:
    name: chart/$CI_MERGE_REQUEST_IID
    action: stop
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true

deploy_review:
  stage: review
  needs: ["deploy_helm_chart"]
  image: debian:bullseye
  variables:
    GIT_STRATEGY: none # We do not need the source code
  tags:
    - docker
  before_script:
    - apt-get update && apt-get install -y git j2cli curl
  script:
    - git config --global user.email "labs@magenta-aps.dk"
    - git config --global user.name "OS2MO Config Updater"
    - git clone https://$DEPLOY_USER:$ACCESS_TOKEN@git.magenta.dk/labs/salt-automation.git
    - cd salt-automation/flux/clusters/os2mo-ci-magenta-az/
    - |
      extra_config="
      ---
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: os2mo
      spec:
        chart:
          spec:
            version: \"$REVIEW_VERSION\""
    - ./template.sh chart-mr$CI_MERGE_REQUEST_IID "$extra_config"
    - git add kustomization.yaml chart-mr$CI_MERGE_REQUEST_IID
    - git status
    - git commit -m "[cd] Deploy OS2MO-Helm-Chart MR$CI_MERGE_REQUEST_IID to flux CI cluster" || true
    - git push || true
    - curl $REVIEW_URL/version/
      --fail
      --retry-all-errors
      --retry-delay 5
      --retry 120
  environment:
    name: review/$CI_MERGE_REQUEST_IID
    url: $REVIEW_URL
    on_stop: stop_review
    auto_stop_in: 1 week
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true

stop_review:
  stage: review
  needs: []
  image: debian:bullseye
  variables:
    GIT_STRATEGY: none # We do not need the source code
  tags:
    - docker
  before_script:
    - apt-get update && apt-get install -y git j2cli
  script:
    - git config --global user.email "labs@magenta-aps.dk"
    - git config --global user.name "OS2MO Config Updater"
    - git clone https://$DEPLOY_USER:$ACCESS_TOKEN@git.magenta.dk/labs/salt-automation.git
    - cd salt-automation/flux/clusters/os2mo-ci-magenta-az/
    - ./untemplate.sh chart-mr$CI_MERGE_REQUEST_IID
    - git add kustomization.yaml chart-mr$CI_MERGE_REQUEST_IID
    - git status
    - git commit -m "[cd] Undeploy OS2MO-Helm-Chart MR$CI_MERGE_REQUEST_IID from flux CI cluster" || true
    - git push || true
  environment:
    name: review/$CI_MERGE_REQUEST_IID
    action: stop
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true


# Release stage
###############

Release to Dev:
  extends: .release-to-dev
  needs: ["Release version"]
  variables:
    ENDPOINT: os2mo/flux/helm/update-dev

Release to Test:
  extends: .release-to-test
  needs: []
  variables:
    ENDPOINT: os2mo/flux/helm/update-test

Release to Prod:
  extends: .release-to-prod
  needs: []
  variables:
    ENDPOINT: os2mo/flux/helm/update-prod
