# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Global
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .venv/
    - .cache/pip
    - .cache/pre-commit

stages:
  - lint
  - test

# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------
.install-deps-template: &install-deps
  before_script:
    # Install pre-commit
    - pip install pre-commit
    # Install yamllint
    - pip install yamllint
    # Install shellcheck
    - apt-get update && apt-get install -y shellcheck
    # Install Helm
    - curl https://baltocdn.com/helm/signing.asc | apt-key add -
    - apt-get update && apt-get install -y apt-transport-https coreutils
    - |-
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" |
        tee /etc/apt/sources.list.d/helm-stable-debian.list
    - apt-get update && apt-get install -y helm

.lint-template: &lint
  <<: *install-deps
  image: python:3.8
  stage: lint

.test-template: &test
  <<: *install-deps
  image: python:3.8
  stage: test

# ---------------------------------------------------------------------------
# Lint
# ---------------------------------------------------------------------------
Lint Project:
  <<: *lint
  script:
    - pre-commit run --all-files

# ---------------------------------------------------------------------------
# Test
# ---------------------------------------------------------------------------
Generate Project:
  <<: *test
  script:
    - helm template --kube-version 1.19.11 chart/
