# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v0.12.1
    hooks:
      - id: reuse

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: helmlint
      - id: shellcheck
      # - id: markdown-link-check
