# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
os2mo:
  image:
    tag: 3.4.8
  graphql:
    enabled: true
  gunicorn:
    max_workers: 2
  init:
    enabled: false
    image:
      tag: latest
    config:
      root_organisation:
        name: xyz
        user_key: 702d97ea-4e03-11ec-8163-c70f41b96b32
      facets:
        org_unit_address_type:
          PhoneUnit:
            title: "CVR"
            scope: "CVR"
      it_systems: {}

keycloak:
  builder:
    lora_realm_enabled: true
    lora_dipex_client_enabled: true
    environment:
      KEYCLOAK_SSL_REQUIRED_MO: none
      KEYCLOAK_SSL_REQUIRED_LORA: none
      KEYCLOAK_REALM_USERS: '[
        {
          "username": "bruce",
          "password": "bruce",
          "firstname": "Bruce",
          "lastname": "Lee",
          "email": "bruce@kung.fu",
          "roles": ["admin"],
          "enabled": true
        }
      ]'
  startupProbe:
    initialDelaySeconds: 90

omada:
  cronjob_schedule: "0/2 * * * *"

load_fixture: true
