# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
os2mo:
  replicaCount: 1
  gunicorn:
    max_workers: 1
  init:
    enabled: false
    image:
      tag: latest
    config:
      root_organisation:
        name: xyz
        user_key: 702d97ea-4e03-11ec-8163-c70f41b96b32
      facets:
        org_unit_address_type:
          PhoneUnit:
            title: "CVR"
            scope: "CVR"
      it_systems: {}
    log_level: DEBUG
  environment:
    GRAPHQL_ENABLE: true
    KEYCLOAK_VERIFY_AUDIENCE: false
  resources:
    requests:
      memory: "1024Mi"
      cpu: "500m"
    limits:
      memory: "1536Mi"
      cpu: "1000m"

lora:
  init:
    make_superuser: true

keycloak:
  builder:
    lora_realm_enabled: true
    lora_dipex_client_enabled: true
    environment:
      KEYCLOAK_SSL_REQUIRED_MO: none
      KEYCLOAK_SSL_REQUIRED_LORA: none
      KEYCLOAK_REALM_USERS: '[
        {
          "username": "bruce",
          "password": "bruce",
          "firstname": "Bruce",
          "lastname": "Lee",
          "email": "bruce@kung.fu",
          "roles": ["admin"],
          "enabled": true
        }
      ]'
  resources:
    requests:
      memory: "2048Mi"
      cpu: "1000m"
    limits:
      memory: "4096Mi"
      cpu: "2000m"

omada:
  cronjob_schedule: "0/2 * * * *"

fixture: "kolding"
