# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: v1
kind: Secret
metadata:
  name: dipex-secret
stringData:
{{- range $key, $val := $.Values.dipex.secrets }}
  {{ $key | quote }}: {{ $val | quote}}
{{- end }}
