# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dipex-config
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "dipex.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
{{- range $key, $val := $.Values.dipex.settings }}
  {{ $key | quote }}: {{ $val | quote }}
{{- end }}
