# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    app: keycloak
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      volumes:
        - name: keycloak-json
          emptyDir: {}
        - name: keycloak-realm-json
          emptyDir: {}
      containers:
        - name: keycloak-json-server
          image: nginx
          volumeMounts:
            - name: keycloak-json
              mountPath: /usr/share/nginx/html
              readOnly: true
        - name: keycloak
          image: quay.io/keycloak/keycloak:14.0.0
          env:
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-secret
                  key: admin_password

            - name: KEYCLOAK_IMPORT
              value: /keycloak-realm-json/keycloak-realm.json
            - name: KEYCLOAK_FRONTEND_URL
              value: "https://testos2mo.silkeborg.dk/auth/"
            - name: PROXY_ADDRESS_FORWARDING
              value: 'true'

            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_ADDR
              value: {{ .Values.database.host }}
            - name: DB_DATABASE
              value: keycloak
            - name: DB_SCHEMA
              value: public
            - name: DB_USER
              value: "keycloak{{ .Values.database.username_suffix }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: db_password
            - name: JDBC_PARAMS
              value: "sslmode={{ .Values.database.sslmode }}"
          volumeMounts:
            - name: keycloak-realm-json
              mountPath: /keycloak-realm-json
              readOnly: true
          # Liveness probe configuration
          livenessProbe:
            httpGet:
              path: /auth/
              port: 8080
            initialDelaySeconds: 0
            timeoutSeconds: 5
          # Readiness probe configuration
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
          # Startup probe configuration
          startupProbe:
            httpGet:
              path: /auth/
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            failureThreshold: 60
            periodSeconds: 5
      initContainers:
        - name: keycloak-init
          image: "{{ .Values.keycloak.init.image.repository }}:{{ .Values.keycloak.init.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.init.image.pullPolicy }}
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.database.host }}
            - name: POSTGRES_USER
              value: "{{ .Values.database.user }}{{ .Values.database.username_suffix }}"
            - name: POSTGRES_SSL
              value: {{ .Values.database.sslmode }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mox-db-secret
                  key: db_password

            # The below are intentionally without suffix
            - name: KEYCLOAK_DB_NAME
              value: "keycloak"
            - name: KEYCLOAK_DB_USER
              value: "keycloak"
            - name: KEYCLOAK_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: db_password

        - name: keycloak-gen
          image: "{{ .Values.keycloak.builder.image.repository }}:{{ .Values.keycloak.builder.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.builder.image.pullPolicy }}
          env:
            - name: KEYCLOAK_JSON_PATH
              value: /keycloak-json/keycloak.json
            - name: KEYCLOAK_REALM_JSON_PATH
              value: /keycloak-realm-json/keycloak-realm.json
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: /auth/
            - name: KEYCLOAK_MO_CLIENT_REDIRECT_URI
              value: https://testos2mo.silkeborg.dk/*
            - name: KEYCLOAK_MO_CLIENT_WEB_ORIGIN
              value: https://testos2mo.silkeborg.dk
          volumeMounts:
            - name: keycloak-json
              mountPath: /keycloak-json
            - name: keycloak-realm-json
              mountPath: /keycloak-realm-json
