# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-gen-config
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
{{- range $key, $val := .Values.keycloak.builder.environment }}
{{ $key | quote | indent 6}}: {{ $val | quote }}
{{- end}}
