# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{ if .Values.keycloak.admin_password }}
stringData:
  admin_password: {{ .Values.keycloak.admin_password }}
{{ else }}
    secret-generator.v1.mittwald.de/autogenerate: admin_password
data: {}
{{ end }}
