# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    app: keycloak
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      volumes:
        - name: keycloak-realm-json
          emptyDir: {}
      containers:
        - name: keycloak
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          args: [
              "-b", "0.0.0.0",
              "-Dkeycloak.migration.action=import",
              "-Dkeycloak.migration.provider=singleFile",
              "-Dkeycloak.migration.file=/keycloak-realm-json/keycloak-realm.json",
              "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
          ]
          env:
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-secret
                  key: admin_password

            - name: KEYCLOAK_FRONTEND_URL
              value: "https://{{ .Values.ingress.hostname }}/auth/"
            - name: PROXY_ADDRESS_FORWARDING
              value: 'true'

            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_ADDR
              value: {{ .Values.database.host }}
            - name: DB_DATABASE
              value: keycloak
            - name: DB_SCHEMA
              value: public
            - name: DB_USER
              value: "keycloak{{ .Values.database.username_suffix }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: db_password
            {{ if ne .Values.database.sslmode "" }}
            - name: JDBC_PARAMS
              value: "sslmode={{ .Values.database.sslmode }}"
            {{ end }}
          volumeMounts:
            - name: keycloak-realm-json
              mountPath: /keycloak-realm-json
              readOnly: true
          # Liveness probe configuration
          livenessProbe:
            httpGet:
              path: /auth/
              port: 8080
            initialDelaySeconds: 0
            timeoutSeconds: 5
          # Readiness probe configuration
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
          # Startup probe configuration
          startupProbe:
            httpGet:
              path: /auth/
              port: 8080
            initialDelaySeconds: 300
            timeoutSeconds: 1
            failureThreshold: 60
            periodSeconds: 5
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
      initContainers:
        - name: keycloak-init
          image: "{{ .Values.keycloak.init.image.repository }}:{{ .Values.keycloak.init.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.init.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.db }}
            - name: POSTGRES_HOST
              value: {{ .Values.database.host }}
            - name: POSTGRES_USER
              value: "{{ .Values.database.user }}"
            - name: POSTGRES_USER_SUFFIX
              value: "{{ .Values.database.username_suffix }}"
            {{ if ne .Values.database.sslmode "" }}
            - name: POSTGRES_SSL
              value: {{ .Values.database.sslmode }}
            {{ end }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{ if .Values.database.password_secret }}
                  name: {{ .Values.database.password_secret }}
                  {{ else }}
                  name: mox-db-secret
                  {{ end }}
                  key: db_password

            # The below are intentionally without suffix
            - name: KEYCLOAK_DB_NAME
              value: "keycloak"
            - name: KEYCLOAK_DB_USER
              value: "keycloak"
            - name: KEYCLOAK_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: db_password
          resources:
            requests:
              memory: "64Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "1000m"
        - name: keycloak-gen
          image: "{{ .Values.keycloak.builder.image.repository }}:{{ .Values.keycloak.builder.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.builder.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: keycloak-gen-config
          env:
            - name: KEYCLOAK_REALM_JSON_PATH
              value: /keycloak-realm-json/keycloak-realm.json
            {{- $is_https := empty .Values.ingress.tls_secret }}
            {{- $protocol := ternary "http" "https" $is_https }}
            - name: KEYCLOAK_MO_CLIENT_REDIRECT_URI
              value: "[\"{{ $protocol }}://{{ .Values.ingress.hostname }}/*\"]"
            - name: KEYCLOAK_MO_CLIENT_WEB_ORIGIN
              value: "[\"{{ $protocol }}://{{ .Values.ingress.hostname }}\"]"
            - name: KEYCLOAK_DIPEX_CLIENT_ENABLED
              value: 'true'
            - name: KEYCLOAK_DIPEX_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-dipex-secret
                  key: client_secret
            - name: KEYCLOAK_LORA_DIPEX_CLIENT_ENABLED
              value: "{{ .Values.keycloak.builder.lora_dipex_client_enabled }}"
            - name: KEYCLOAK_LORA_DIPEX_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-lora-dipex-secret
                  key: client_secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "1000m"
          volumeMounts:
            - name: keycloak-realm-json
              mountPath: /keycloak-realm-json
