# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    app: keycloak
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      volumes:
        - name: keycloak-json
          emptyDir: {}
        - name: keycloak-realm-json
          emptyDir: {}
      containers:
        - name: keycloak-json-server
          image: nginx
          volumeMounts:
            - name: keycloak-json
              mountPath: /usr/share/nginx/html
              readOnly: true
        - name: keycloak
          image: quay.io/keycloak/keycloak:14.0.0
          env:
            - name: DB_VENDOR
              value: H2
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin  # XXX: Use an autogenerated secret
            - name: KEYCLOAK_IMPORT
              value: /keycloak-realm-json/keycloak-realm.json
            - name: PROXY_ADDRESS_FORWARDING
              value: 'true'
            - name: KEYCLOAK_FRONTEND_URL
              value: https://testos2mo.silkeborg.dk/auth/
          volumeMounts:
            - name: keycloak-realm-json
              mountPath: /keycloak-realm-json
              readOnly: true
      initContainers:
        - name: keycloak-gen
          image: "{{ .Values.keycloak.builder.image.repository }}:{{ .Values.keycloak.builder.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.builder.image.pullPolicy }}
          env:
            - name: KEYCLOAK_JSON_PATH
              value: /keycloak-json/keycloak.json
            - name: KEYCLOAK_REALM_JSON_PATH
              value: /keycloak-realm-json/keycloak-realm.json
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: /auth/
            # TODO: Further keycloak configuration here
            - name: KEYCLOAK_MO_CLIENT_REDIRECT_URI
              value: https://testos2mo.silkeborg.dk/*
            - name: KEYCLOAK_MO_CLIENT_WEB_ORIGIN
              value: https://testos2mo.silkeborg.dk
          volumeMounts:
            - name: keycloak-json
              mountPath: /keycloak-json
            - name: keycloak-realm-json
              mountPath: /keycloak-realm-json
