# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mo-deployment
  labels:
    app: mo
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.os2mo.replicaCount }}
  selector:
    matchLabels:
      app: mo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mo
    spec:
      containers:
        - name: mo
          image: "{{ .Values.os2mo.image.repository }}:{{ .Values.os2mo.image.tag }}"
          imagePullPolicy: {{ .Values.os2mo.image.pullPolicy }}
          env:
            - name: PORT
              value: "8080"

            # Disable service platformen
            - name: DUMMY_MODE
              value: "true"

            - name: LORA_URL
              value: "http://mox-service:80/"

            # Confdb
            - name: CONF_DB_USE
              value: "false"

            # Keycloak
            - name: KEYCLOAK_SCHEMA
              value: http
            - name: KEYCLOAK_PORT
              value: "8080"
            - name: KEYCLOAK_HOST
              value: "keycloak-service"
            {{- $is_https := empty .Values.ingress.tls_secret }}
            {{- $protocol := ternary "http" "https" $is_https }}
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: "{{ $protocol }}://{{ .Values.ingress.hostname }}/auth/"

          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1536Mi"
              cpu: "250m"
      initContainers:
        - name: wait-for-mox
          image: curlimages/curl
          command: ["/bin/sh","-c"]
          args: ['echo -e "Waiting for MOX to be ready\c"; while [ $(curl -ksw "%{http_code}" "http://mox-service/site-map" -o /dev/null) -ne 200 ]; do sleep 1; echo -e ".\c"; done; echo "OK"']
          resources:
            requests:
              memory: "64Mi"
              cpu: "5m"
            limits:
              memory: "128Mi"
              cpu: "10m"
{{ if .Values.load_fixture }}
        - name: fixture-loader
          image: magentaaps/os2mo-kolding-fixture:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.database.host }}
            {{ if ne .Values.database.sslmode "" }}
            - name: POSTGRES_SSL
              value: {{ .Values.database.sslmode }}
            {{ end }}
            - name: POSTGRES_NAME
              value: "mox"
            - name: POSTGRES_USER
              value: "mox{{ .Values.database.username_suffix }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mox-secret
                  key: db_password
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
{{ end }}
      restartPolicy: Always
