# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mo-deployment
  labels:
    app: mo
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.os2mo.replicaCount }}
  selector:
    matchLabels:
      app: mo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mo
    spec:
      containers:
        - name: mo
          image: "{{ .Values.os2mo.image.repository }}:{{ .Values.os2mo.image.tag }}"
          imagePullPolicy: {{ .Values.os2mo.image.pullPolicy }}
          env:
            - name: LORA_URL
              value: "http://mox-service:80/"
            - name: CONF_DB_HOST
              value: {{ .Values.database.host }}
            - name: CONF_DB_PORT
              value: "5432"
            - name: CONF_DB_NAME
              value: "mora"
            - name: CONF_DB_USER
              value: "mora"
            - name: CONF_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mo-secret
                  key: db_password
          ports:
            - containerPort: 80
      initContainers:
        - name: wait-for-mox
          image: curlimages/curl
          command: ["/bin/sh","-c"]
          args: ['echo -e "Waiting for MOX to be ready\c"; while [ $(curl -ksw "%{http_code}" "http://mox-service/site-map" -o /dev/null) -ne 200 ]; do sleep 1; echo -e ".\c"; done; echo "OK"']
{{ if .Values.load_fixture }}
        - name: fixture-loader
          image: magentaaps/os2mo-kolding-fixture:latest
          imagePullPolicy: Always
          env:
            - name: PGHOST
              value: {{ .Values.database.host }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mox-secret
                  key: db_password
{{ end }}
      restartPolicy: Always
