# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{ if .Values.ingress.tls_secret }}
{{ if .Values.ingress.tls_cert.key }}
{{ if .Values.ingress.tls_cert.cert }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.ingress.tls_secret }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "os2mo.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
stringData:
  tls.key: {{ .Values.ingress.tls_cert.key | quote }}
  tls.crt: {{ .Values.ingress.tls_cert.cert | quote }}
{{ end }}
{{ end }}
{{ end }}
