# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
{{- if .Values.os2mo.init.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: os2mo-init-config
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "os2mo-init.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  config: |
{{ toYaml .Values.os2mo.init.config | indent 4}}
{{- end }}
