# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mo-ingress
  annotations:
{{ if eq .Values.ingress.class "nginx" }}
    kubernetes.io/ingress.class: nginx
{{ if .Values.ingress.basic_auth }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: mo-ingress-basic-auth-secret
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - OS2mo'
{{ end }}
{{ end }}
spec:
  {{ if .Values.ingress.tls_secret }}
  tls:
    - hosts:
       - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.tls_secret }}
  {{ end }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mo-service
                port:
                  number: 80
  {{ if .Values.ingress.hostname }}
      host: {{ .Values.ingress.hostname }}
  {{ end }}
