# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: mo-service
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: mo

  # TODO: remove later - necessary for now due to https://redmine.magenta-aps.dk/issues/47372
  #sessionAffinity: ClientIP

  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
