# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: mo-service
spec:
  selector:
    app: mo
  ports:
    - name: "80"
      port: 80
      targetPort: 80
