# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mox-deployment
  labels:
    app: mox
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.lora.replicaCount }}
  selector:
    matchLabels:
      app: mox
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mox
    spec:
      containers:
        - name: mox
          image: "{{ .Values.lora.image.repository }}:{{ .Values.lora.image.tag }}"
          imagePullPolicy: {{ .Values.lora.image.pullPolicy }}
          env:
            - name: DB_HOST
              value: {{ .Values.database.host }}
            {{ if ne .Values.database.sslmode "" }}
            - name: DB_SSLMODE
              value: {{ .Values.database.sslmode }}
            {{ end }}
            - name: DB_NAME
              value: "mox"
            - name: DB_USER
              value: "mox{{ .Values.database.username_suffix }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mox-secret
                  key: db_password
            - name: DB_EXTENSIONS_PATH
              value: "oio_rest/oio_rest/db_extensions/mo-01.json"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "250m"
      initContainers:
        - name: mox-init
          image: "{{ .Values.lora.init.image.repository }}:{{ .Values.lora.init.image.tag }}"
          imagePullPolicy: {{ .Values.lora.init.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.db }}
            - name: POSTGRES_HOST
              value: {{ .Values.database.host }}
            - name: POSTGRES_USER
              value: "{{ .Values.database.user }}"
            - name: POSTGRES_USER_SUFFIX
              value: "{{ .Values.database.username_suffix }}"
            {{ if ne .Values.database.sslmode "" }}
            - name: POSTGRES_SSL
              value: {{ .Values.database.sslmode }}
            {{ end }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mox-db-secret
                  key: db_password

            # The below are intentionally without suffix
            - name: DB_NAME
              value: "mox"
            - name: DB_USER
              value: "mox"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mox-secret
                  key: db_password

            - name: SESSIONS_DB_NAME
              value: "sessions"
            - name: SESSIONS_DB_USER
              value: "sessions"
            - name: SESSIONS_DB_PASSWORD
              value: "sessions"

            - name: CONF_DB_NAME
              value: "mora"
            - name: CONF_DB_USER
              value: "mora"
            - name: CONF_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mo-secret
                  key: db_password
          resources:
            requests:
              memory: "64Mi"
              cpu: "5m"
            limits:
              memory: "128Mi"
              cpu: "10m"
      restartPolicy: Always
