# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{ if .Values.database.password_secret }}
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: mox-db-secret
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{ if .Values.database.external }}
{{ else }}
    secret-generator.v1.mittwald.de/autogenerate: db_password
{{ end }}
  labels:
    {{- include "mox-db.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{ if .Values.database.external }}
stringData:
  db_password: {{ .Values.database.password }}
{{ else }}
data: {}
{{ end }}
{{ end }}
