# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: mox-service
spec:
  selector:
    app: mox
  ports:
    - name: "80"
      port: 80
      targetPort: 80
