# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{ if .Values.database.external }}
{{ else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.host }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "mox-db.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "mox-db.selectorLabels" . | nindent 4 }}
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
{{ end }}
