# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mox-deployment
  labels:
    app: mox
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.lora.replicaCount }}
  selector:
    matchLabels:
      app: mox
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mox
    spec:
      containers:
        - name: mox
          image: "{{ .Values.lora.image.repository }}:{{ .Values.lora.image.tag }}"
          imagePullPolicy: {{ .Values.lora.image.pullPolicy }}
          env:
            - name: DB_HOST
              value: {{ .Values.database.host }}
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "mox"
            - name: DB_USER
              value: "mox"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mox-secret
                  key: db_password
            - name: DB_EXTENSIONS
              value: "oio_rest/oio_rest/db_extensions/mo-01.json"
          ports:
            - containerPort: 80
      initContainers:
        - name: mox-init
          image: "{{ .Values.lora.init.image.repository }}:{{ .Values.lora.init.image.tag }}"
          imagePullPolicy: {{ .Values.lora.init.image.pullPolicy }}
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.database.host }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mox-db-secret
                  key: db_password

            - name: DB_NAME
              value: "mox"
            - name: DB_USER
              value: "mox"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mox-secret
                  key: db_password

            - name: SESSIONS_DB_NAME
              value: "sessions"
            - name: SESSIONS_DB_USER
              value: "sessions"
            - name: SESSIONS_DB_PASSWORD
              value: "sessions"

            - name: CONF_DB_NAME
              value: "mora"
            - name: CONF_DB_USER
              value: "mora"
            - name: CONF_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mo-secret
                  key: db_password
      restartPolicy: Always
