# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: mox-db-service
spec:
  selector:
    app: mox-db
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
