# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: v1
kind: Secret
metadata:
  name: mox-secret
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: db_password
data: {}
