# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.omada.enabled }}
# v1beta1 necessary for Kubernetes versions < 1.21
apiVersion: {{ ternary "batch/v1beta1" "batch/v1" (.Capabilities.APIVersions.Has "batch/v1beta1/CronJob") }}
kind: CronJob
metadata:
  name: omada-sync-cronjob
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "omada-cronjob.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: {{ .Values.omada.cronjob_schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "omada-cronjob.labels" . | nindent 8 }}
        spec:
          containers:
            - name: omada-sync-cronjob
              image: curlimages/curl
              command: ["/bin/sh","-c"]
              args: [ 'curl -X POST "http://omada-service:8080/import/it-users"' ]
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "5m"
                limits:
                  memory: "128Mi"
                  cpu: "10m"
          initContainers:
            - name: wait-for-omada
              image: curlimages/curl
              command: ["/bin/sh","-c"]
              args: ['echo -e "Waiting for Omada to be ready\c"; while [ $(curl -ksw "%{http_code}" "http://omada-service:8080/ready" -o /dev/null) -ne 200 ]; do sleep 1; echo -e ".\c"; done; echo "OK"']
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "5m"
                limits:
                  memory: "128Mi"
                  cpu: "10m"
          restartPolicy: OnFailure
{{- end }}
