# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.omada.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omada-deployment
  labels:
    app: omada
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: omada
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: omada
    spec:
      containers:
        - name: omada
          image: "{{ .Values.omada.image.repository }}:{{ .Values.omada.image.tag }}"
          imagePullPolicy: {{ .Values.omada.image.pullPolicy }}
          env:
            - name: MO_URL
              value: "http://mo-service:5000"
            - name: AUTH_SERVER
              value: "http://keycloak-service:8080/auth"
            - name: AUTH_REALM
              value: "mo"
            - name: CLIENT_ID
              value: "dipex"
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-dipex-secret
                  key: client_secret
            - name: IT_SYSTEM_USER_KEY
              value: "{{ .Values.omada.it_system_user_key }}"
            - name: ODATA_URL
              value: "{{ .Values.omada.odata_url }}"
            - name: MAX_WORKERS
              value: "1"
            {{- if .Values.omada.host_header }}
            - name: OMADA_HOST_HEADER
              value: "{{ .Values.omada.host_header }}"
            {{- end }}
            {{- if .Values.omada.ntlm.enabled }}
            - name: OMADA_NTLM_USERNAME
              valueFrom:
                secretKeyRef:
                  name: omada-ntlm-secret
                  key: ntlm_username
            - name: OMADA_NTLM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: omada-ntlm-secret
                  key: ntlm_password
            {{- end }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.omada.resources | nindent 12 }}
      initContainers:
        {{ include "wait-for-keycloak" . | nindent 8 }}
        {{ include "wait-for-mox" . | nindent 8 }}
        {{ include "wait-for-mo" . | nindent 8 }}
        - name: os2mo-init
          image: "{{ .Values.os2mo.init.image.repository }}:{{ .Values.os2mo.init.image.tag }}"
          imagePullPolicy: {{ .Values.os2mo.init.image.pullPolicy }}
          env:
            - name: AUTH_SERVER
              value: "http://keycloak-service:8080/auth"
            - name: MO_URL
              value: "http://mo-service:5000"
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-dipex-secret
                  key: client_secret
            - name: LORA_URL
              value: "http://mox-service:8080"
            - name: LORA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-lora-dipex-secret
                  key: client_secret
            - name: LORA_AUTH_REALM
              value: "lora"
          resources:
            {{- toYaml .Values.initContainers.resources | nindent 12 }}
          volumeMounts:
           - name: omada-init-config-volume
             mountPath: /config
             readOnly: true
      volumes:
        - name: omada-init-config-volume
          configMap:
            name: omada-init-config
            items:
              - key: config
                path: config.yml
{{- end }}
