# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.omada.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: omada-service
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "omada.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "omada.selectorLabels" . | nindent 4 }}
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
{{- end }}
