# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.sd_changed_at.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: sd-changed-at-service
  labels:
    app: sdtool
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: sd-changed-at
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
{{- end }}
