# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: v1
kind: Secret
metadata:
  name: sd-secret
data:
  sd_username: c2RzZAo=
  sd_password: c2RzZAo=
  sd_institution: WFkK
