# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.sdtool.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: sdtool-service
  labels:
    app: sdtool
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: sdtool
  ports:
    - name: "80"
      port: 80
      targetPort: 80
{{- end }}
