# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.sdtool.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sdtool-config
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
{{ toYaml .Values.sdtool.environment | indent 2 }}
{{- end }}
