# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.sdtool.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdtool
  labels:
    app: sdtool
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: sdtool
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sdtool
    spec:
      containers:
        - name: sdtool
          image: "{{ .Values.sdtool.image.registry }}/{{ .Values.sdtool.image.repository }}:{{ .Values.sdtool.image.tag }}"
          imagePullPolicy: {{ .Values.sdtool.image.pullPolicy }}
          env:
            - name: MORA_URL
              value: "http://mo-service:5000"
            - name: AUTH_SERVER
              value: "http://keycloak-service:8080/auth"
            - name: AUTH_REALM
              value: "mo"
            - name: CLIENT_ID
              value: "integration-sdtool"
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: integration-sdtool-keycloak-client
                  key: client_secret

            # The three ENVs below require an sd-secret created in Flux

            - name: SD_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sdtool.sd_secret_name }}
                  key: sd_username
            - name: SD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sdtool.sd_secret_name }}
                  key: sd_password
            - name: SD_INSTITUTION_IDENTIFIER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sdtool.sd_secret_name }}
                  key: sd_institution

            - name: SD_TOO_DEEP
              value: {{ .Values.sdtool.sd_too_deep | quote }}

          envFrom:
            - configMapRef:
                name: sdtool-config
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.sdtool.resources | nindent 12 }}
{{- end }}
