# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trust-config
data:
  # OS2Sync Requires two certificates for each environment (test/prod)
  # These are changed regularly and can be found at https://digitaliseringskataloget.dk/teknik/certifikater
  # Relevant docs for os2sync: https://www.os2sync.dk/downloads/Installation%20Guide.pdf
  # Relevant  errors from OS2sync:
  #   - `SOAP signature received from STS does not validate!`
  #
  # new_ORG_PROD_Organisation_2.cer
  prod-org.cer: |
    -----BEGIN CERTIFICATE-----
    MIIGYDCCBJSgAwIBAgIUZgcFbQZGl6PcpyHCR6pH1zcxy7cwQQYJKoZIhvcNAQEK
    MDSgDzANBglghkgBZQMEAgEFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgEF
    AKIDAgEgMFYxLTArBgNVBAMMJERlbiBEYW5za2UgU3RhdCBPQ0VTIHVkc3RlZGVu
    ZGUtQ0EgMTEYMBYGA1UECgwPRGVuIERhbnNrZSBTdGF0MQswCQYDVQQGEwJESzAe
    Fw0yNjAxMDkwOTI1NDJaFw0yOTAxMDgwOTI1NDFaMIGWMSAwHgYDVQQDDBdPUkdf
    UFJPRF9PcmdhbmlzYXRpb25fMjE3MDUGA1UEBRMuVUk6REstTzpHOmE5Mzk5NWQ0
    LWE4ZWQtNGZjZC1iMTA0LWUzOWIzNmE1ODc5ZTETMBEGA1UECgwKS09NQklUIEEv
    UzEXMBUGA1UEYQwOTlRSREstMTk0MzUwNzUxCzAJBgNVBAYTAkRLMIIBojANBgkq
    hkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAv+GkHgtrZWiBVp3leWC2gJRQI/Qsa9Cm
    A6i5NK9dJb5L88kfVe63/s+j205mywou5qabKm5/eNXUE0e+8cQTm7ww2HzR45u+
    hlSNcORrdFdYbr5gd42lk1Yq+ZaOXuyZ9RwvxDDZKDFjjTH1IYKrv2VeK+Oeufev
    yyEmM6gAOKfdErHPMtTEA2UjxlfLh4zKZVrnCSKt+hE/b4bv+D7AKNE7Q3UW+w9b
    L09rMFgN0AP90uWg8VNlVKXRp7HeA4dKT54oDxrrALm53T1SpuUQz0Q/v1o8FUzf
    woUCeAvjrbaFx0fkyCP/LW6J76EtPBTt/Pfv/sfUBLDT013rFc3mPs2L3/sDBBXd
    q+MCCCP3star9N9MVrqO4nKOyVRr1sR6e0fS9lrhjdxumLsWdgbPLHcRTeoQ8rQm
    MX+gHkumrwbKbXBBQfmzWi4H8ng1KNbrtenIVC0xlCpXosl0+CPqpRMTC3jTbslL
    yIQpKlM60sBIwcg1ABUEoPwK+zt0M8GZAgMBAAGjggF7MIIBdzAMBgNVHRMBAf8E
    AjAAMB8GA1UdIwQYMBaAFEwB4spzvMO+OAo4PTawXHSce5e5MHMGCCsGAQUFBwEB
    BGcwZTA/BggrBgEFBQcwAoYzaHR0cDovL2NhMS5nb3YuZGsvb2Nlcy9pc3N1aW5n
    LzEvY2FjZXJ0L2lzc3VpbmcuY2VyMCIGCCsGAQUFBzABhhZodHRwOi8vY2ExLmdv
    di5kay9vY3NwMCIGA1UdIAQbMBkwCAYGBACPegEBMA0GCyqBUIEpAQEBAwcBMDsG
    CCsGAQUFBwEDBC8wLTArBggrBgEFBQcLAjAfBgcEAIvsSQECMBSGEmh0dHBzOi8v
    dWlkLmdvdi5kazBBBgNVHR8EOjA4MDagNKAyhjBodHRwOi8vY2ExLmdvdi5kay9v
    Y2VzL2lzc3VpbmcvMS9jcmwvaXNzdWluZy5jcmwwHQYDVR0OBBYEFGi1ygIaSCvz
    V14bgqd3RybiDswOMA4GA1UdDwEB/wQEAwIFoDBBBgkqhkiG9w0BAQowNKAPMA0G
    CWCGSAFlAwQCAQUAoRwwGgYJKoZIhvcNAQEIMA0GCWCGSAFlAwQCAQUAogMCASAD
    ggGBACgWh7vewUREwPd9OGCtLNWiVtxsgv0YGl8TnQEpRWPv/RhRoP1gUys6Ts22
    FKvTQ6CeEh/T7z2QQgo+7vJPA0HHI6QRBgq1ap4lGqjox2FyvrlNw+VP65tu2ecw
    HNmyPSzTQNohNW+LMIhA4LvN4tPdurSoNsXNOLeDusutjpqEBsuI51b/WEpzKizM
    24Fo9s4kUVZtsKV+vqvxPBf/akHVcPioa9aSXLqMbCc6FA2Ys+xIfjMNjiMl+P3i
    t+wciDG0VrZZ+oFz0WaHTEwBBoo8qUY5XEP4POGj8kIF/A9XmbHH9LbzT5g81g9x
    G8YwyDGf3me/KIbloGBOFtN5jdJ28M8N/GmxQY2SK/zlHeKqwPsOMFHcX2v71rzU
    B8jDDAmlGS99NIGHpPKrvyc5NV4Oz6EprAZbH+ASAs4jMRsWn+1Ed9oFdQ1CrHU1
    TAeVYZv4ru2px2LYAaaZ9kYfu6R+ChOoZsIPH2mE22My2F9Gptp7I8BW4+18Neyx
    8JJQ/g==
    -----END CERTIFICATE-----

  # ORG_EXTTEST_Organisation_2.cer
  test-org.cer: |
    -----BEGIN CERTIFICATE-----
    MIIGYzCCBJegAwIBAgIURkwNMyl3Cua9Hc9+eVZxKDpPZIYwQQYJKoZIhvcNAQEK
    MDSgDzANBglghkgBZQMEAgEFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgEF
    AKIDAgEgMFYxLTArBgNVBAMMJERlbiBEYW5za2UgU3RhdCBPQ0VTIHVkc3RlZGVu
    ZGUtQ0EgMTEYMBYGA1UECgwPRGVuIERhbnNrZSBTdGF0MQswCQYDVQQGEwJESzAe
    Fw0yNTEyMTIxMDMwMDlaFw0yODEyMTExMDMwMDhaMIGZMSMwIQYDVQQDDBpPUkdf
    RVhUVEVTVF9PcmdhbmlzYXRpb25fMjE3MDUGA1UEBRMuVUk6REstTzpHOjgwZDQy
    OTBlLTM0YzktNGE3OC05M2NmLTM1OTQxNjJmODRmYzETMBEGA1UECgwKS09NQklU
    IEEvUzEXMBUGA1UEYQwOTlRSREstMTk0MzUwNzUxCzAJBgNVBAYTAkRLMIIBojAN
    BgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAnxMBzmyrDewAudPFLnxiDtS6Xmor
    QWXxI5vs4iGKfzCRz9JUJBsoaFzxOyENxRwWeN9evTMqzbA1sBeZhqKi8YckrKIe
    vX6tfBfCv3RJLMFCi9bVvJrpMHCWZh7e5d34a44RPMtDN3qFy0MdW/uJ27yZnVeJ
    KN91WyaTsQC6AGzci4DuNXpQN1s+xT6nPQvGZOfe3e2XSNCFxzpqk+WI93I7g8PS
    XN2jqWThqQ97i4+xc1OMDiZVI5WCaqK2JQsAVE9Gz3WC5WGTbR6kFUBIIQhMrq6W
    q6bCR2sjaz1U3pWII5j4FMGCsglXbL4qDiiyAqahO0X7Kk5OAEtK6SwTF0RKh2oP
    7ugCaAVJKwZQ+lNoZxhdAJcTt0RCxkYx/HYq4Usc50U+07zaz0naIHQSf064qX4P
    LL5VQy/zBJTabIkQX76fqcMIAndOVou3El1OB1YXa4t4AiwnugTx2AkpVA1vZjUX
    Vmdul5grtwkqGzIwO1kQE6isZ75h8n1CdLb7AgMBAAGjggF7MIIBdzAMBgNVHRMB
    Af8EAjAAMB8GA1UdIwQYMBaAFEwB4spzvMO+OAo4PTawXHSce5e5MHMGCCsGAQUF
    BwEBBGcwZTA/BggrBgEFBQcwAoYzaHR0cDovL2NhMS5nb3YuZGsvb2Nlcy9pc3N1
    aW5nLzEvY2FjZXJ0L2lzc3VpbmcuY2VyMCIGCCsGAQUFBzABhhZodHRwOi8vY2Ex
    Lmdvdi5kay9vY3NwMCIGA1UdIAQbMBkwCAYGBACPegEBMA0GCyqBUIEpAQEBAwcB
    MDsGCCsGAQUFBwEDBC8wLTArBggrBgEFBQcLAjAfBgcEAIvsSQECMBSGEmh0dHBz
    Oi8vdWlkLmdvdi5kazBBBgNVHR8EOjA4MDagNKAyhjBodHRwOi8vY2ExLmdvdi5k
    ay9vY2VzL2lzc3VpbmcvMS9jcmwvaXNzdWluZy5jcmwwHQYDVR0OBBYEFNCJHYOy
    ZEZn/+Z/FQO3G5tjb+W5MA4GA1UdDwEB/wQEAwIFoDBBBgkqhkiG9w0BAQowNKAP
    MA0GCWCGSAFlAwQCAQUAoRwwGgYJKoZIhvcNAQEIMA0GCWCGSAFlAwQCAQUAogMC
    ASADggGBAF/RCUYjJAaJUqD/7Yx5+KVtY9xyjDymmb3+zTEP/tlz7eKHSfYDYIHZ
    ZX4vb8OwPNQEdTq5aT9+Aalc4FlXOrldzg9O0VHnnO9Mtj6FBGjzhC3AoskSjsd/
    ckvvvh0+uj2w4vEk/CBbwKv/4SfAJWfPnge+0EnL5QA4zZ6eYM+iLEN59TwQxqxF
    lEQXYs4MHRqdo60IzQB2mBOI9UDtHbdOPP3R290w8jkSUob/U5FcLHddHVl6l1JA
    7aprJwG7K/2UqcDyjpPmCA/ffbZEYPtP8wV4DoCKgybs5bTHaif4d7sAG8Vm/Zpv
    AboQe5vfQc69nhFOrhEI0g1tMu2YGYNTB6S329dKs8v87lwjlyknA8rWdVZ+yt/9
    AWZiJGgrCzgU3POnnfx6jdOsnazZCQHbpOc2frniERlIT+1LZ3k6TnMt4jwEC4kj
    C+fBTfAwRazK0bd/N/euMCm4cbtHHqW5k5WYTAgJR9EtHI3XykFaZMO9BCzVmk/M
    7AX/TRN/OA==
    -----END CERTIFICATE-----

  # ADG_PROD_Adgangsstyring_2.cer
  prod-sts.cer: |
    -----BEGIN CERTIFICATE-----
    MIIGYjCCBJagAwIBAgIUC16645a/E0MdEXQjKsrlDQfv514wQQYJKoZIhvcNAQEK
    MDSgDzANBglghkgBZQMEAgEFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgEF
    AKIDAgEgMFYxLTArBgNVBAMMJERlbiBEYW5za2UgU3RhdCBPQ0VTIHVkc3RlZGVu
    ZGUtQ0EgMTEYMBYGA1UECgwPRGVuIERhbnNrZSBTdGF0MQswCQYDVQQGEwJESzAe
    Fw0yNDA4MzAxMTI2MDZaFw0yNzA4MzAxMTI2MDVaMIGYMSIwIAYDVQQDDBlBREdf
    UFJPRF9BZGdhbmdzc3R5cmluZ18yMTcwNQYDVQQFEy5VSTpESy1POkc6YzhjNzU1
    MGEtYjg0NC00ODBjLTg4ZTYtY2QzZjdmNzZmNGZjMRMwEQYDVQQKDApLT01CSVQg
    QS9TMRcwFQYDVQRhDA5OVFJESy0xOTQzNTA3NTELMAkGA1UEBhMCREswggGiMA0G
    CSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQCk4gJd+S6b0pZov7RgRqYva6oHXRCS
    Gv0Ua/ndlZjyC4TBjf76AQf8yQ+A5zPPamIX9NcSUqjrfwHDu6GHA583PS9FZExR
    vv57pa8u9E99W2CIzETj4LSCwDBFnzKvDKkOn/9vnk+Yk5IhzK3PkOMFe+K4IKxZ
    MN01iG/Mt0TGvjnbZRbII3iXA6Ld1osUEHFJCrvg7w9t6VBJBA6Giz6XVvZ1axoN
    DGwsM7ES/A/VjYlXQSg0YaUaUOra+QHKtcTVhtmNh1KS0cwvFXk1AsP672t71HMP
    6mdkV98U50RWbzWztSq0ecsURQ4vylUA/IRno2uax0QV6DJGF86GnP46HnpU3rto
    s7GTfpFExV/JWLv9I1Z2SQkUUOMnOEDWfEePbfkO6oS7jpZ9ng/oNPM9gXogB4ce
    cqw63SK9xhPWHuY+qFkQ9BA6C6c3NXZp/m74v5h44Vp0TDEdaVDQhtta6PxfrXuM
    zZZ/eVhgQwxGUNnXOYllDHHD4htGUaPU9icCAwEAAaOCAXswggF3MAwGA1UdEwEB
    /wQCMAAwHwYDVR0jBBgwFoAUTAHiynO8w744Cjg9NrBcdJx7l7kwcwYIKwYBBQUH
    AQEEZzBlMD8GCCsGAQUFBzAChjNodHRwOi8vY2ExLmdvdi5kay9vY2VzL2lzc3Vp
    bmcvMS9jYWNlcnQvaXNzdWluZy5jZXIwIgYIKwYBBQUHMAGGFmh0dHA6Ly9jYTEu
    Z292LmRrL29jc3AwIgYDVR0gBBswGTAIBgYEAI96AQEwDQYLKoFQgSkBAQEDBwEw
    OwYIKwYBBQUHAQMELzAtMCsGCCsGAQUFBwsCMB8GBwQAi+xJAQIwFIYSaHR0cHM6
    Ly91aWQuZ292LmRrMEEGA1UdHwQ6MDgwNqA0oDKGMGh0dHA6Ly9jYTEuZ292LmRr
    L29jZXMvaXNzdWluZy8xL2NybC9pc3N1aW5nLmNybDAdBgNVHQ4EFgQUSY948C6h
    R49PT1wBNfBK4vGLDj8wDgYDVR0PAQH/BAQDAgWgMEEGCSqGSIb3DQEBCjA0oA8w
    DQYJYIZIAWUDBAIBBQChHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAIBBQCiAwIB
    IAOCAYEAiej+/RSjp7oWdV9e+rBTFaZAt8BxhbSfPCIfCHuOYl0lNgBtG5crUoXf
    68LOGIM9AkqbrB4eC6laqT7+xYwtVvz7q+fo/i85eyO/u7gwzDb2AjA45VvbNeBG
    c509gU2gsGASn5aSEtGHzJElJmaqVI3Xqls6YHnJngjIl3QLnVStfBeMjUhn8yFv
    AgO47QYLECCB2i0Mz1erH7uSti5MX3jq0Q2QONBqjSbKgWCni8oR49tH783xBWRd
    kRGFdIIsG3fycVyPJj32Vq5C6lUQLq480yGAfI6h3fXcpeAJ0dtzngnkAuZIs10O
    +SqsbIvk8MQ4166SmKDx2vynmTp6EqxGys9/ECNl98L8GhlEbt2n0mMX9WRe0Jqq
    DDHtm0ONly1wb3FPX/MZ4MvynPeTKakWXJ0Ei2yPppox4BL49GuBts0jLTI6QCk2
    oDpsTJIyOOOI2HI+7UPca50J2IDimx5+OjHuWGHw6TiaRTKh7/uDjI4YRwhOwKXv
    FvDnFd/I
    -----END CERTIFICATE-----

  # ADG_EXTTEST_Adgangsstyring_2.cer
  test-sts.cer: |
    -----BEGIN CERTIFICATE-----
    MIIGZTCCBJmgAwIBAgIUTl4VV4Pb3i+ChtHu0c+TOgBAomAwQQYJKoZIhvcNAQEK
    MDSgDzANBglghkgBZQMEAgEFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgEF
    AKIDAgEgMFYxLTArBgNVBAMMJERlbiBEYW5za2UgU3RhdCBPQ0VTIHVkc3RlZGVu
    ZGUtQ0EgMTEYMBYGA1UECgwPRGVuIERhbnNrZSBTdGF0MQswCQYDVQQGEwJESzAe
    Fw0yNTEyMTIxMDMxMTRaFw0yODEyMTExMDMxMTNaMIGbMSUwIwYDVQQDDBxBREdf
    RVhUVEVTVF9BZGdhbmdzc3R5cmluZ18yMTcwNQYDVQQFEy5VSTpESy1POkc6OWI0
    OTlhNGQtNDM3NC00MWRlLTg1NDAtNTA0NjgyZWMxZTQ2MRMwEQYDVQQKDApLT01C
    SVQgQS9TMRcwFQYDVQRhDA5OVFJESy0xOTQzNTA3NTELMAkGA1UEBhMCREswggGi
    MA0GCSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQC8lQgxipGLw2nsdNSOh9RuVdv7
    S6x38ABenKWb+mb/HAffBEGnbOp2k7zNCqhcAG2c3M+QjtlopcPLPnLXTG47iS1z
    A/6wiR1fuQwmImASEkjziskhPMwqJ4jVnsPIrSjXgkP1yK8F9CEdwi10kFelmq2L
    B5dV/WFdjgeIAtZ2MAKGCMCxl0qGVzuMzU/gqPDenC/7sDtUUc9G6ZFOaBtGavSi
    sJVCtxN5NXkshgp9bvWVN2P0RRxLqjdxW3DbRYKkBNp0v/ZsgjAY0PQk9XwX9ulL
    PBQb1p6J8La3IuhjV5wF8OiM8Fv5FoxBElyrOPxitxQxW9pEbAfyQEEU7Z8tmFg8
    2Py0XAIpa6ldXzeTZVimz8fc/ZHQ9Gng5rnpZF0dfBj/xWyHco7xfn7geq2rKE8L
    lAz27UkYs/1U3gPHA33F1a3/I4x6kGfVFK/+/a2jCSCRY8/flLELhuFCxqSvNUB9
    UNoLzMdHb5XeJhnrPrjPQCuQmLSWC4lrrpvKAhcCAwEAAaOCAXswggF3MAwGA1Ud
    EwEB/wQCMAAwHwYDVR0jBBgwFoAUTAHiynO8w744Cjg9NrBcdJx7l7kwcwYIKwYB
    BQUHAQEEZzBlMD8GCCsGAQUFBzAChjNodHRwOi8vY2ExLmdvdi5kay9vY2VzL2lz
    c3VpbmcvMS9jYWNlcnQvaXNzdWluZy5jZXIwIgYIKwYBBQUHMAGGFmh0dHA6Ly9j
    YTEuZ292LmRrL29jc3AwIgYDVR0gBBswGTAIBgYEAI96AQEwDQYLKoFQgSkBAQED
    BwEwOwYIKwYBBQUHAQMELzAtMCsGCCsGAQUFBwsCMB8GBwQAi+xJAQIwFIYSaHR0
    cHM6Ly91aWQuZ292LmRrMEEGA1UdHwQ6MDgwNqA0oDKGMGh0dHA6Ly9jYTEuZ292
    LmRrL29jZXMvaXNzdWluZy8xL2NybC9pc3N1aW5nLmNybDAdBgNVHQ4EFgQUsCW9
    fymcqHUW6OPDZ8qfrv6x3WwwDgYDVR0PAQH/BAQDAgWgMEEGCSqGSIb3DQEBCjA0
    oA8wDQYJYIZIAWUDBAIBBQChHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAIBBQCi
    AwIBIAOCAYEAIA35y5eymgmiXA7+mfhIEvIOlA4r3uBX4O7klussFS/2IMJlk/1K
    ZdHhMXNoK80uvdqHD7Wtx6HyAO1Igc9ct7TYdjn6kCQ656/ad8CWBByEALlVWoyx
    MBprUnB7t89gsk8AnHGPj1nm9ObDxQspQBMHJ8v0mN4b4mnO7xC0yYrg5s5d58Md
    MHoqwor0U85HET7PuYztY7xagXdg8q/icwRFSaRQuGGqz5YAcITJjMk/9JqpyP98
    QRruO1XoPR0bawuk4Z4ZEnkNGpMfr8vha1fF2stVlI6Fo1veJvEKfcj5LXZ86fgN
    A6fPZRVEMhfodJxe6oeI2GKeij1RowL5sDobge1rQbFQB92+b5/wP95qr7gU3e/I
    CXWdLsga6LNKEf8ylXhc8csojH8fGE76RxSIzy3DNS17gnrobL6088emudCNOuZw
    n0fdu93reZbyCqbA5V3/0QUlIA0aCqqcWRHPHDnpv1tYy87SFjeR8B/6HFzH8B06
    T7XeDLxkMwTi
    -----END CERTIFICATE-----
