# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.ad_to_mo_sync.enabled }}
{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ad-to-mo-sync
  labels:
    app: ad-to-mo-sync
spec:
  selector:
    matchLabels:
      app: ad-to-mo-sync
  endpoints:
    - port: "8000"
      metricRelabelings:
        - action: keep
          regex: "amqp_publish_last_published|amqp_publish|amqp_publish_exceptions|amqp_publish_inprogress|amqp_publish_seconds|dipex_.+"
          sourceLabels:
            - __name__
{{- end }}
{{- end }}
