# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.sd_changed_at.enabled }}
{{- $keycloak_client_id := "integration_sd_changed_at" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-changed-at
  labels:
    app: sd-changed-at
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd-changed-at
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sd-changed-at
    spec:
      containers:
        - name: sd-changed-at
          image: "{{ .Values.sd_changed_at.image.registry }}/{{ .Values.sd_changed_at.image.repository }}:{{ .Values.sd_changed_at.image.tag }}"
          env:
            {{- if not .Values.sd_changed_at.sd_global_from_date }}
              {{- fail "SD_GLOBAL_FROM_DATE must be set" }}
            {{- end }}
            {{- if not .Values.sd_changed_at.sd_job_function }}
              {{- fail "SD_JOB_FUNCTION must be set" }}
            {{- end }}
            {{- if not .Values.sd_changed_at.sd_monthly_hourly_divide }}
              {{- fail "SD_MONTHLY_HOURLY_DIVIDE must be set" }}
            {{- end }}
            - name: SD_GLOBAL_FROM_DATE
              value: "{{ .Values.sd_changed_at.sd_global_from_date }}"
            - name: SD_JOB_FUNCTION
              value: "{{ .Values.sd_changed_at.sd_job_function }}"
            - name: SD_MONTHLY_HOURLY_DIVIDE
              value: "{{ .Values.sd_changed_at.sd_monthly_hourly_divide }}"

            {{ if .Values.sentry.environment }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sentry.secret }}
                  key: dsn
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.sentry.environment | quote }}
            {{ end }}

            - name: MO_URL
              value: "http://mo-service:5000"
            - name: AUTH_SERVER
              value: "http://keycloak-service:8080/auth"
            - name: AUTH_REALM
              value: "mo"
            - name: CLIENT_ID
              value: "{{ $keycloak_client_id }}"
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sd-changed-at-client-secret
                  key: client_secret

            # The three ENVs below require an sd-secret created in Flux

            - name: SD_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sd_changed_at.sd_secret_name }}
                  key: sd_username
            - name: SD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sd_changed_at.sd_secret_name }}
                  key: sd_password
            - name: SD_INSTITUTION_IDENTIFIER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sd_changed_at.sd_secret_name }}
                  key: sd_institution
            {{- range $name, $value := .Values.sd_changed_at.environment }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            - name: PGHOST
              value: {{ .Values.database.host }}
            - name: APP_DATABASE
              value: {{ .Values.sd_changed_at.db.name }}
            - name: APP_DBUSER
              value: {{ .Values.sd_changed_at.db.user }}
            - name: APP_DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sd_changed_at.sd_secret_name }}
                  key: app_dbpassword
          {{- if .Values.sd_changed_at.number_of_days_to_persist_logs_to_files }}
            - name: LOG_TO_FILE
              value: "true"
            - name: LOG_FILE_BACKUP_COUNT
              value: {{ .Values.sd_changed_at.number_of_days_to_persist_logs_to_files | quote }}
          volumeMounts:
            - name: sd-pv
              mountPath: /var/log/sdlon
          {{- end }}
          ports:
            - containerPort: 5000
          resources:
            {{- toYaml .Values.sd_changed_at.resources | nindent 12 }}
      initContainers:
        {{ include "os2mo.wait-for-keycloak" . | nindent 8 }}
        {{ include "os2mo.wait-for-mo" . | nindent 8 }}
        - name: create-client-secret
          image: "{{ .Values.keycloak.integrationbuilder.image.registry }}/{{ .Values.keycloak.integrationbuilder.image.repository }}:{{ .Values.keycloak.integrationbuilder.image.tag }}"
          env:
            {{ include "os2mo.keycloak_terraform_db_connection" .  | nindent 12 }}
            - name: POSTGRES_SCHEMA_NAME
              value: terraform_remote_state_sd_changed_at

            # Keycloak REST connection
            - name: TF_VAR_admin_password
              valueFrom:
                secretKeyRef:
                  name: {{ include "os2mo.keycloak_admin_secret" . }}
                  key: admin_password

            # Configuration of the client
            - name: TF_VAR_client_name
              value: "{{ $keycloak_client_id }}"
            - name: TF_VAR_client_roles
              value: '["admin", "service_api"]'
            - name: TF_VAR_client_secret
              valueFrom:
                secretKeyRef:
                  name: sd-changed-at-client-secret
                  key: client_secret
            - name: TF_VAR_client_uuid
              value: "5dc4a1ce-baad-c0de-7364-6368616e6765"
          resources:
            {{- toYaml .Values.initContainers.resources | nindent 12 }}
        - name: sd-db-init
          image: "{{ .Values.sd_changed_at.db.init.image.registry }}/{{ .Values.sd_changed_at.db.init.image.repository }}:{{ .Values.sd_changed_at.db.init.image.tag }}"
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.database.host }}
            - name: POSTGRES_USER
              value: {{ .Values.database.user }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{ if .Values.database.password_secret }}
                  name: {{ .Values.database.password_secret }}
                  {{ else }}
                  name: mox-db-secret
                  {{ end }}
                  key: db_password
            # The ENVs below are named KEYCLOAK_... since we are currently using
            # the Keycloak DB init-container. This will be fixed in
            # see https://redmine.magenta-aps.dk/issues/57967
            - name: KEYCLOAK_DB_NAME
              value: {{ .Values.sd_changed_at.db.name | quote }}
            - name: KEYCLOAK_DB_USER
              value: {{ .Values.sd_changed_at.db.user | quote }}
            - name: KEYCLOAK_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sd_changed_at.sd_secret_name }}
                  key: app_dbpassword
          resources:
            {{- toYaml .Values.initContainers.resources | nindent 12 }}
      {{- if .Values.sd_changed_at.number_of_days_to_persist_logs_to_files }}
      volumes:
        - name: sd-pv
          # PVC must be provided via Flux Kustomization
          persistentVolumeClaim:
            claimName: sd-pvc
      {{- end }}
{{- end }}
