# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{ if .Values.keycloak.admin_secret }}
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
    secret-generator.v1.mittwald.de/encoding: base32
    secret-generator.v1.mittwald.de/autogenerate: admin_password
data: {}
{{ end }}
