# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{ if not .Values.keycloak.admin_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "os2mo.keycloak_admin_secret" . }}
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
    secret-generator.v1.mittwald.de/encoding: base32
    secret-generator.v1.mittwald.de/autogenerate: admin_password
data: {}
{{ end }}
