# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
{{- if .Values.keycloak.builder.lora_realm_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-lora-client
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
    secret-generator.v1.mittwald.de/encoding: base32
    secret-generator.v1.mittwald.de/autogenerate: client_secret
data: {}
{{- end }}
