# SPDX-FileCopyrightText: Magenta ApS
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}-helm-pre-delete-terraform"
rules:
  - apiGroups: ["infra.contrib.fluxcd.io"]
    resources: [terraforms]
    verbs: [list, delete, watch]  # 'watch' is required to wait for deletion in kubectl
