# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if and (.Values.sdtool_plus.enabled) (.Values.sdtool_plus.cronjob_sd_job_functions_enabled) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-sd-job-functions-sdtool-plus
  labels:
    app: sdtool-plus
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.sdtool_plus.cronjob_sd_job_functions_schedule | quote }}
  timeZone: {{ .Values.timezone | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-sd-job-functions-sdtool-plus
              image: curlimages/curl
              command: ["/bin/sh","-c"]
              args: [ 'curl --silent --show-error --fail-with-body -X POST "http://sdtool-plus-service:8000/job-functions/sync?institution_identifier={{ .Values.sdtool_plus.cronjob_sd_job_functions_institution_identifier }}"' ]
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "5m"
                limits:
                  memory: "128Mi"
                  cpu: "10m"
          initContainers:
            {{ include "os2mo.wait-for-sdtool-plus" . | nindent 12 }}
          restartPolicy: OnFailure
{{- end }}
