# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.sdtool_plus.minisync.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sdtool-plus-minisync-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.sdtool_plus.minisync.ingress.basicAuthSecret }}
    nginx.ingress.kubernetes.io/auth-realm: 'minisync'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
       - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.tls_secret }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /minisync
            pathType: Prefix
            backend:
              service:
                name: sdtool-plus-service
                port:
                  number: 8000
{{- end }}
