---
# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
{{- if .Values.os2mo_smtp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: os2mo-smtp
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: os2mo-smtp
  template:
    metadata:
      labels:
        app: os2mo-smtp
    spec:
      containers:
        - name: os2mo-smtp
          image: "{{ .Values.os2mo_smtp.image.registry }}/{{ .Values.os2mo_smtp.image.repository }}:{{ .Values.os2mo_smtp.image.tag }}"
          env:
            - name: FASTRAMQPI__MO_URL
              value: "http://mo-service:5000"
            - name: FASTRAMQPI__CLIENT_ID
              value: "dipex"
            - name: FASTRAMQPI__AUTH_SERVER
              value: "http://keycloak-service:8080/auth"
            - name: FASTRAMQPI__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-dipex-secret
                  key: client_secret
            {{ if .Values.amqp.enabled }}
            - name: FASTRAMQPI__AMQP__URL
              valueFrom:
                secretKeyRef:
                  name: amqp-url-secret
                  key: url
            {{ end }}
            {{ toYaml .Values.os2mo_smtp.extraEnv | indent 12 | trim }}
              # Database
            - name: FASTRAMQPI__DATABASE__USER
              value: "smtp"
            - name: FASTRAMQPI__DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: os2mo-smtp-database-secret
                  key: database_password
            - name: FASTRAMQPI__DATABASE__HOST
              value: {{ .Values.database.host }}
            - name: FASTRAMQPI__DATABASE__NAME
              value: "smtp"
          resources:
            {{- toYaml .Values.os2mo_smtp.resources | nindent 12 }}
{{- end }}
