# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.orggatekeeper.enabled }}
{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orggatekeeper
  labels:
    app: orggatekeeper
spec:
  selector:
    matchLabels:
      app: orggatekeeper
  endpoints:
  - port: "8000"
{{- end }}
{{- end }}
