# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.xflow.enabled }}
{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xflow
  labels:
    app: xflow
spec:
  selector:
    matchLabels:
      app: xflow
  endpoints:
    - port: "8000"
      metricRelabelings:
        - action: keep
          regex: "amqp_publish_last_published|amqp_publish|amqp_publish_exceptions|amqp_publish_inprogress|amqp_publish_seconds|dipex_.+"
          sourceLabels:
            - __name__
{{- end }}
{{- end }}
